const students = [
	{ id: 2, name: "Svart", image: "assets/images/students/svart.png" },
	{ id: 3, name: "Grå", image: "assets/images/students/grå.png" },
	{ id: 4, name: "Vinröd", image: "assets/images/students/vinröd.png" },
	{ id: 6, name: "Röd", image: "assets/images/students/röd.png" },
	{ id: 7, name: "Orange", image: "assets/images/students/orange.png" },
	{ id: 8, name: "Gul", image: "assets/images/students/gul.png" },
	{ id: 9, name: "Grön", image: "assets/images/students/grön.png" },
	{ id: 10, name: "Blå", image: "assets/images/students/blå.png" },
	{ id: 11, name: "Mörkblå", image: "assets/images/students/mörkblå.png" },
	{ id: 12, name: "Lila", image: "assets/images/students/lila.png" },
	{ id: 13, name: "Lavendel", image: "assets/images/students/lavendel.png" },
	{ id: 14, name: "Rosa", image: "assets/images/students/rosa.png" },
	{ id: 15, name: "Brun", image: "assets/images/students/brun.png" },
	{ id: 16, name: "Ceriserosa", image: "assets/images/students/ceriserosa.png" },
	{ id: 17, name: "Blågrön", image: "assets/images/students/blågrön.png" },
	{ id: 18, name: "Himmelsblå", image: "assets/images/students/himmelsblå.png" },
	{ id: 20, name: "Mörklila", image: "assets/images/students/mörklila.png" },
	{ id: 21, name: "Guld", image: "assets/images/students/guld.png" },
	{ id: 22, name: "Ljusgul", image: "assets/images/students/ljusgul.png" },
	{ id: 25, name: "Mörkgul", image: "assets/images/students/mörkgul.png" },
	{ id: 26, name: "Plommon", image: "assets/images/students/plommon.png" },
	{ id: 27, name: "Ljusgrå", image: "assets/images/students/ljusgrå.png" },
	{ id: 28, name: "Indigo", image: "assets/images/students/indigo.png" },
	{ id: 29, name: "Gröngul", image: "assets/images/students/gröngul.png" },
	{ id: 30, name: "Olivgrön", image: "assets/images/students/olivgrön.png" },
]